//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Data.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Practices.EnterpriseLibrary.Data.System.Data.Common.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;{0}&apos; is empty..
        /// </summary>
        internal static string ADP_EmptyString {
            get {
                return ResourceManager.GetString("ADP_EmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config Base Elements Only.
        /// </summary>
        internal static string ConfigBaseElementsOnly {
            get {
                return ResourceManager.GetString("ConfigBaseElementsOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config Base No Child Nodes.
        /// </summary>
        internal static string ConfigBaseNoChildNodes {
            get {
                return ResourceManager.GetString("ConfigBaseNoChildNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config Provider Invalid.
        /// </summary>
        internal static string ConfigProviderInvalid {
            get {
                return ResourceManager.GetString("ConfigProviderInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config Provider Missing.
        /// </summary>
        internal static string ConfigProviderMissing {
            get {
                return ResourceManager.GetString("ConfigProviderMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config Provider Not Found.
        /// </summary>
        internal static string ConfigProviderNotFound {
            get {
                return ResourceManager.GetString("ConfigProviderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config Provider Not Installed.
        /// </summary>
        internal static string ConfigProviderNotInstalled {
            get {
                return ResourceManager.GetString("ConfigProviderNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config Required Attribute Empty.
        /// </summary>
        internal static string ConfigRequiredAttributeEmpty {
            get {
                return ResourceManager.GetString("ConfigRequiredAttributeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config Required Attribute Missing.
        /// </summary>
        internal static string ConfigRequiredAttributeMissing {
            get {
                return ResourceManager.GetString("ConfigRequiredAttributeMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config Sections Unique.
        /// </summary>
        internal static string ConfigSectionsUnique {
            get {
                return ResourceManager.GetString("ConfigSectionsUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config Unrecognized Attributes.
        /// </summary>
        internal static string ConfigUnrecognizedAttributes {
            get {
                return ResourceManager.GetString("ConfigUnrecognizedAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config Unrecognized Element.
        /// </summary>
        internal static string ConfigUnrecognizedElement {
            get {
                return ResourceManager.GetString("ConfigUnrecognizedElement", resourceCulture);
            }
        }
    }
}
